version: '3.5'

services:
  backend:
    container_name: backend
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - web-network
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - ./app/backend-vhost-80.conf:/etc/apache2/sites-available/000-default.conf
      - ./app:/var/www/html

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - web-network
    ports:
      - "5432:5432"

networks:
  web-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
volumes:
  db-data:
