name: PHP Test Suite

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем Ubuntu как базовую операционную систему

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >  # Опциональный аргумент для указания дополнительных опций для сервиса
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker-compose up -d --build
          docker exec -it backend ip link
          docker exec -it backend make firstUp

      - name: Run tests
        run: |
          docker exec backend php artisan test

      - name: Cleanup
        run: |
          docker-compose -f docker-compose.yml down  # Останавливаем контейнеры