name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        volumes:
          - db-data:/var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run tests
        run: |
          docker-compose -f ./docker-compose.yml up -d --build
          docker-compose -f ./docker-compose.yml exec backend ./vendor/bin/phpunit
          docker-compose -f ./docker-compose.yml down

    volumes:
      db-data:
