name: CI

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run containers
        run: |
          docker-compose down -v
          docker-compose up -d --build
          docker exec backend ip link
          docker exec backend make firstUp

      - name: Run tests
        run: |
          make test

      - name: Cleanup
        run: |
          docker-compose down -v